name: CD Pipeline - production

on:
  release:
    types: [published]

jobs:
  terraform:
    name: 'Deploy to production'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        with:
          version_label: ${{ github.event.release.tag_name }}
          version_description: ${{ github.SHA }}
        run: echo $version_label
